name: Build

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Build Main
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.2.2
        target: esp32s3
        path: '.'
